<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="MavenFirstAutomation" duration-ms="40" started-at="2016-05-22T05:30:39Z" finished-at="2016-05-22T05:30:39Z">
    <groups>
    </groups>
    <test name="Test Execution On Chrome" duration-ms="40" started-at="2016-05-22T05:30:39Z" finished-at="2016-05-22T05:30:39Z">
      <class name="com.StringJava.IntConcept">
        <test-method status="FAIL" signature="reverseINT_VAL()[pri:0, instance:com.StringJava.IntConcept@1a407d53]" name="reverseINT_VAL" is-config="true" duration-ms="0" started-at="2016-05-22T11:00:39Z" finished-at="2016-05-22T11:00:39Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at com.StringJava.IntConcept.reverseINT_VAL(IntConcept.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:220)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reverseINT_VAL -->
        <test-method status="PASS" signature="revers()[pri:0, instance:com.StringJava.IntConcept@1a407d53]" name="revers" duration-ms="0" started-at="2016-05-22T11:00:39Z" finished-at="2016-05-22T11:00:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- revers -->
      </class> <!-- com.StringJava.IntConcept -->
      <class name="com.StringJava.App">
        <test-method status="PASS" signature="hello()[pri:0, instance:com.StringJava.App@3498ed]" name="hello" is-config="true" duration-ms="10" started-at="2016-05-22T11:00:39Z" finished-at="2016-05-22T11:00:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hello -->
        <test-method status="PASS" signature="method2()[pri:0, instance:com.StringJava.App@3498ed]" name="method2" duration-ms="0" started-at="2016-05-22T11:00:39Z" finished-at="2016-05-22T11:00:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method2 -->
      </class> <!-- com.StringJava.App -->
    </test> <!-- Test Execution On Chrome -->
  </suite> <!-- MavenFirstAutomation -->
</testng-results>
